http://localhost:8080/currency_exchange_api_war/currencies

###
http://localhost:8080/currency_exchange_api_war/currency/EUR

###
http://localhost:8080/currency_exchange_api_war/exchangeRates

###
http://localhost:8080/currency_exchange_api_war/exchangeRate/USDRUB

###
http://localhost:8080/currency_exchange_api_war/exchangeRate/RUBUSD

###
http://localhost:8080/currency_exchange_api_war/exchangeRate/RUBEUR